const appInterfaces: any = [
  {
    lang: 'en',
    placeholder: 'Search...',
    capital: 'Capital',
    USD: 'Dollar USA',
    EUR: 'Euro',
    BYN: 'Belarussian RUB',
    TRY: 'Turkish lira',
    RUB: 'Russian ruble',
    CNY: 'Chinese yuan',
    JPY: 'Japanese yen',
    EGP: 'Egyptian pound',
    GBP: 'Pound sterling',
    backTo: 'Back to all countries',
    noFound: 'Not Found',
    signInBtn: 'Sign In',
    signUpBtn: 'Sign Up',
    signIn: 'Sign In',
    signUp: 'Registration',
    submit: 'Submit',
    email: 'Enter  e-mail',
    password: 'Enter password',
    confirmPassword: 'Confirm password',
    username: 'Enter your name',
    photo: 'Photo',
  },
  {
    lang: 'ru',
    placeholder: 'Поиск...',
    capital: 'Столица',
    USD: 'Доллар США',
    EUR: 'Евро',
    BYN: 'Белорусский рубль',
    TRY: 'Турецкая лира',
    RUB: 'Российский рубль',
    CNY: 'Китайский юань',
    JPY: 'Японская иена',
    EGP: 'Египетский фунт',
    GBP: 'Фунт стерлингов',
    backTo: 'Назад к списку стран',
    noFound: 'Ничего не найдено',
    signInBtn: 'Войти',
    signUpBtn: 'Зарегистрироваться',
    signIn: 'Вход в аккаунт',
    signUp: 'Регистрация',
    submit: 'Подтвердить',
    email: 'Введите e-mail',
    password: 'Введите пароль',
    confirmPassword: 'Подтвердите пароль',
    username: 'Введите ваше имя',
    photo: 'Фото',
  },
  {
    lang: 'be',
    placeholder: 'Пошук...',
    capital: 'Сталіца',
    USD: 'Долар ЗША',
    EUR: 'Еўра',
    BYN: 'Беларускi рубель',
    TRY: 'Турэцкая ліра',
    RUB: 'Расійскі рубель',
    CNY: 'Кітайскі юань',
    JPY: 'Японская ена',
    EGP: 'Егіпецкі фунт',
    GBP: 'Фунт стэрлінгаў',
    backTo: 'Назад да спісу краін',
    noFound: 'Нічога не знойдзена',
    signInBtn: 'Увайсці',
    signUpBtn: 'Зарэгістравацца',
    signIn: 'Уваход у акаўнт',
    signUp: 'Рэгістрацыя',
    submit: 'Пацвердзіць',
    email: 'Увядзіце e-mail',
    password: 'Увядзіце пароль',
    confirmPassword: 'Пацвердзіце пароль',
    username: 'Увядзіце ваша імя',
    photo: 'Фота',
  },
];

export default appInterfaces;
