const appInterfaces: any = [
  {
    lang: 'en',
    placeholder: 'Search...',
    capital: 'Capital',
    USD: 'Dollar USA',
    EUR: 'Euro',
    BYN: 'Belarussian RUB',
    TRY: 'Turkish lira',
    RUB: 'Russian ruble',
    CNY: 'Chinese yuan',
    JPY: 'Japanese yen',
    EGP: 'Egyptian pound',
    GBP: 'Pound sterling',
    backTo: 'Back to all countries',
  },
  {
    lang: 'ru',
    placeholder: 'Поиск...',
    capital: 'Столица',
    USD: 'Доллар США',
    EUR: 'Евро',
    BYN: 'Белорусский рубль',
    TRY: 'Турецкая лира',
    RUB: 'Российский рубль',
    CNY: 'Китайский юань',
    JPY: 'Японская иена',
    EGP: 'Египетский фунт',
    GBP: 'Фунт стерлингов',
    backTo: 'Назад к списку стран',
  },
  {
    lang: 'by',
    placeholder: 'Пошук...',
    capital: 'Сталіца',
    USD: 'Долар ЗША',
    EUR: 'Еўра',
    BYN: 'Беларускi рубель',
    TRY: 'Турэцкая ліра',
    RUB: 'Расійскі рубель',
    CNY: 'Кітайскі юань',
    JPY: 'Японская ена',
    EGP: 'Егіпецкі фунт',
    GBP: 'Фунт стэрлінгаў',
    backTo: 'Назад да спісу краін',
  },
];

export default appInterfaces;
